eggjs/mock

README.md, README.zh_CN.md, index.js, test/fixtures/apps/mockhome/package.json, test/mm.test.js
=> feat: add mm.home

app/extend/application.js, test/ctx.test.js
mm.app
can't override data when mockContext(data), if I call mockContext twice, data has changed.
=> fix: can't override data when mockContext(data)

.travis.yml, README.md, README.zh_CN.md, app/extend/application.js, appveyor.yml, package.json, test/fixtures/apps/mock_cookies/app/router.js, test/fixtures/demo/app/controller/home.js, test/mock_cookies.test.js, test/mock_httpclient.test.js
closes https://github.com/eggjs/egg/issues/243
=> refactor: use mockHttpclient instead of mockUrllib

lib/app.js, test/app.test.js, test/app_event.test.js, test/app_proxy.test.js, test/fixtures/app-event/agent.js, test/fixtures/app-event/app.js, test/fixtures/app-event/app/router.js, test/fixtures/app-event/package.json, test/fixtures/app-proxy-ready/agent.js, test/fixtures/app-proxy-ready/app.js, test/fixtures/app-proxy-ready/package.json, test/fixtures/app-proxy/app/extend/application.js, test/fixtures/app-proxy/package.json, test/fixtures/app/app/router.js
- add defineProperty, deleteProperty, getOwnPropertyDescriptor, getPrototypeOf handler
- cache the events before app init
=> fix: improve proxy handler and event listener

test/fixtures/demo/app/router.js
=> test: remove userrole

lib/request_call_function.js, package.json, test/fixtures/apps/app-throw/app/router.js, test/fixtures/apps/app-throw/config/config.default.js, test/fixtures/apps/app-throw/config/config.unittest.js, test/fixtures/apps/app-throw/package.json, test/mock_cluster_restore.test.js
closes https://github.com/eggjs/egg/issues/888
=> fix: ignore all error on cluster mock restore

app/extend/application.js, test/mock_service.test.js
=> fix: support mock the same property multiple times

bootstrap.js, index.d.ts, index.js, package.json, test/index.test.ts
index.d.ts 重构，直接把 mm 挂到 default 上，同时可以把其他一些 interface 暴露出来，给其他应用使用。
=> chore: refactor d.ts

README.md, README.zh_CN.md, bootstrap.js, index.d.ts, lib/cluster.js
=> feat: support ts

README.md, README.zh_CN.md, index.d.ts, lib/cluster.js, lib/format_options.js, package.json, test/fixtures/apps/foo/app/router.js, test/fixtures/demo-async/app.js, test/fixtures/demo/app.js, test/fixtures/demo/app/context.js, test/fixtures/demo/app/service/old.js, test/fixtures/disable-security/app.js, test/fixtures/disable-security/app/context.js, test/fixtures/disable-security/app/service/old.js, test/fixtures/ts-false/package.json, test/fixtures/ts/package.json, test/format_options.test.js
=> fix: remove options.typescript support

lib/context.js
Can use egg-mock on non-egg project.
=> fix: allow egg-core module missing

index.d.ts
发现通过 declaration merging 的 override 方式还是有问题，会导致 export 出去的就只剩了一个 restore 方法，把原来的 EggMock 覆盖掉了，改回 `restore: () => any`。
=> fix: fix declaration merging error

index.d.ts
egg-mock 中的 [mockHttpclient](https://github.com/eggjs/egg-mock/blob/master/lib/mock_httpclient.js#L33) 参数：mockResult 这个参数中的 data item 本意可以接受 object, string 和 buffer，并最终都转为 buffer string 根据请求的 content-type 来做 response body 的转化。
然而在 egg-mock  的[官方 typing]() 里，却只允许传入 string，因为 JSON 和 Buffer 并不是 TypeScript 内建的类型，所以在 typescript 下并不 work，mockHttpclient 的 data 永远只能接受 string，否则无法通过 tsserver 的编译。
考虑 object 和 Buffer 都是 object，更正 typing 的文件，使得 TypeScript 下 mockHttpclient 可以和 common js 下接受的参数类型表现一致。
=> fix:  remove nonexistent type and correct typing

index.d.ts, package.json
change httpRequest function signature, returns actual type instead of any.
=> fix: fix httpRequest function signature

.travis.yml, lib/mock_httpclient.js, test/mock_httpclient.test.js
修复当 mockResult 为函数时，发起多次请求，函数也只会执行一次的问题（ 原因是 `mockResult = mockResult()` 导致结果被缓存了 ）。
=> fix: mockHttpclient with multi-request

README.md, README.zh_CN.md, app/extend/application.js, lib/cluster.js, test/app.test.js
just like app.expectLog(), but negate
=> feat: support app.notExpectLog()

lib/app.js, test/app.test.js, test/app_proxy.test.js
https://github.com/eggjs/egg/blob/8bb7c7e7d59d6aeca4b2ed1eb580368dcb731a4d/lib/egg.js#L125
如果不设置的话，mm.app({ single }) 后 调用 app.close 会报错，因为 egg 里面的挂载是在 start 里面的，mm.app 没走 start，先这么处理了，等 runtime 里面的 createInstance 下沉后，egg-mock 这块可以改为直接调用它就统一了。
=> fix: single mode will call app.agent.close

lib/app.js, test/app_proxy.test.js, test/fixtures/messenger-binding/agent.js, test/fixtures/messenger-binding/app.js
egg-mock
Replace messenger.sendRandom() method with messenger.sendToApp() or messenger.sendToAgent(). Thus app and agent can normally send to random app/agent in unittest. 
related issue: https://github.com/eggjs/egg/issues/3989 https://github.com/eggjs/egg/issues/4055
reference: https://github.com/eggjs/egg-mock/pull/94/files
=> fix: enable sendRandom() method in unittest

lib/app.js, test/app.test.js
sff mock 那块，还是想改为继承方式，在 mock app init 之前加个钩子，用来初始化代码。
=> feat: support init hook before mock app init

index.d.ts, index.test-d.ts
支持已有 env 类型提示的前提下，也能传入其他环境类型不抛错
=> fix: allow other envtype

.github/workflows/nodejs.yml, bootstrap.js, lib/parallel/agent.js, lib/parallel/agent_register.js, lib/parallel/app.js, lib/parallel/util.js, lib/utils.js, test/parallel.test.js
- use mochaGlobalSetup/mochaGlobalTeardown to setup agent in mocha master process.
- bootstrap app without agent to aviod port conflict.
=> feat: impl parallel app for mocha parallel mode

bootstrap.js, lib/agent.js, lib/parallel/agent_register.js, package.json, register.js
=> feat: use mocha global hook to register before/after

bootstrap.js, lib/agent.js, lib/app.js, lib/parallel/agent.js, lib/parallel/app.js, lib/parallel/util.js, package.json, register.js
=> fix: app should wait for agent ready on parallel mode

lib/inject_context.js, test/fixtures/tegg-app/test/hooks.test.ts
=> fix: every it should has self ctx

lib/app_handler.js, lib/inject_context.js, lib/parallel/agent.js
=> fix: make sure app ready on parallel mode

lib/inject_context.js
=> fix: use symbol to access suite app

register.js, test/fixtures/tegg-app/app.js, test/fixtures/tegg-app/config/config.default.js, test/fixtures/tegg-app/test/multi_mock_context.test.ts, test/fixtures/tegg-app/test/tegg.test.ts, test/fixtures/tegg-app/test/tegg_context.test.ts, test/fixtures/tegg-app/tsconfig.json, test/inject_ctx.test.js
https://github.com/cnpm/cnpmcore/pull/408 avoid app beforeClose logic not coverage problem
=> fix: should close app on afterAll hook

register.js, test/inject_ctx.test.js
https://github.com/eggjs/egg-mock/pull/159
=> fix: disable app close on parallel

.github/workflows/codeql-analysis.yml, .github/workflows/nodejs.yml, .github/workflows/release.yml, package.json
=> fix: set types to index.d.ts
