lib/app.js
=> fix: add eggPath for new egg

lib/cluster.js
传递 opt 给 coffee, 以便传递 execArgv
=> feat: pass opt to coffee

lib/cluster.js
=> feat: cluster should wait process exit

lib/app.js
=> feat: should close agent when app close

lib/app.js, lib/cluster.js
=> feat: wait 10ms to close app

lib/app.js, package.json, test/app.test.js
=> fix: don't use cache when app from cache is closed

README.md, lib/format_options.js, test/agent.test.js, test/app.test.js, test/cluster.test.js, test/ctx.test.js, test/format_options.test.js, test/mm.test.js, test/mock_context.test.js, test/mock_cookies.test.js, test/mock_csrf.test.js, test/mock_env.test.js, test/mock_headers.test.js, test/mock_service.test.js, test/mock_session.test.js, test/mock_urllib.test.js
=> feat: try to lookup egg that will be the default customEgg

index.js
replace the internal link into an github link in the env comment.
=> fix: replace the internal link into an github link in the env comment.

app/extend/application.js, lib/app.js, package.json, test/app.test.js, test/fixtures/app-fail/app/router.js, test/fixtures/app-fail/package.json, test/mock_csrf.test.js, test/mock_service.test.js
- create MockApplication to start agent and app
- use Proxy delegating property to MockApplication
=> feat: reimplement mm.app

.gitignore, lib/app.js, package.json, test/agent.test.js, test/fixtures/agent/agent.js, test/fixtures/agent/app.js, test/fixtures/agent/client.js
=> feat: cluster-client support for mm.app

test/fixtures/apps/env-app/config/config.default.js
=> test: remove unuse codes

lib/app.js, package.json, test/app.test.js, test/app_event.test.js, test/app_proxy.test.js, test/fixtures/apps/env-app/config/config.local.js, test/mm.test.js
https://github.com/eggjs/egg/issues/331
=> feat: [BREAKING_CHANGE] can get error from .ready()

lib/app.js, lib/format_options.js, test/app_proxy.test.js, test/fixtures/apps/env-app/config/config.default.js, test/fixtures/messenger-binding/agent.js, test/fixtures/messenger-binding/app.js, test/fixtures/messenger-binding/package.json, test/mm.test.js
=> fix: bind messenger with app and agent

package.json
=> deps: upgrade egg

lib/app.js
=> fix: app.close in right order

lib/app.js, lib/cluster.js, package.json, test/cluster.test.js, test/fixtures/apps/no-framework/config/plugin.js, test/fixtures/apps/no-framework/package.json, test/fixtures/apps/no-framework/plugin/a/app/extend/application.js, test/fixtures/apps/no-framework/plugin/a/package.json, test/mm.test.js
=> fix: egg-mock is not a framework

app/extend/application.js, test/fixtures/apps/mock_cookies/app/router.js, test/mock_cookies.test.js
=> fix: should pass all arguments when mockCookies

README.md, app/extend/application.js, test/mock_httpclient.test.js
=> feat: mockHttpClient support mock multi methods

README.md, README.zh_CN.md
=> docs: add `mm` link at README.md

README.md, README.zh_CN.md, app/extend/application.js, lib/cluster.js, package.json, test/fixtures/request/app/router.js, test/fixtures/request/config/config.default.js, test/fixtures/request/package.json, test/mock_request.test.js
=> feat: add app.httpRequest() test helper

lib/app.js, test/app_proxy.test.js, test/fixtures/messenger-binding/agent.js, test/fixtures/messenger-binding/app.js
=> feat: should pass when emit egg-ready

app/extend/application.js, test/fixtures/demo/app/controller/home.js
=> feat: mockUrllib support async function

index.d.ts, package.json, test/index.test.ts
=> tsd 配置更新，直接放本地包里

app/extend/application.js, test/fixtures/demo/app/controller/home.js, test/mock_httpclient.test.js
=> fix(httpclient): miss headers on options when emit response

test/cluster.test.js, test/mock_cluster_restore.test.js, test/mock_cluster_without_security_plugin.test.js
=> test: disable coverage when mm.cluster

.travis.yml, README.md, appveyor.yml, bootstrap.js, package.json, test/bootstrap.test.js
=> feat: add bootstrap

app/extend/application.js, lib/app.js, lib/cluster.js, test/fixtures/demo-async/app.js, test/fixtures/demo-async/app/controller/home.js, test/fixtures/demo-async/app/router.js, test/fixtures/demo-async/app/service/bar/foo.js, test/fixtures/demo-async/app/service/foo.js, test/fixtures/demo-async/app/service/third/bar/foo.js, test/fixtures/demo-async/config/config.js, test/fixtures/demo-async/mocks_data/service/bar/foo/get/foobar.js, test/fixtures/demo-async/mocks_data/service/foo/get/foobar.js, test/fixtures/demo-async/package.json, test/mock_service.async.js
=> feat: base promise to support async function

app/extend/application.js, app/middleware/cluster_app_mock.js, lib/cluster.js, lib/request_call_function.js, lib/supertest.js, test/app.test.js, test/cluster.test.js, test/fixtures/demo/app/router.js, test/fixtures/request/app/router.js, test/index.test.ts, test/mock_request.test.js
```js
app.httpRequest()
.get('home')
.expect(200);
```
=> feat: support httpRequest().get(routerName)

README.md, app/extend/application.js, test/mock_httpclient.test.js
=> feat(mockHttpclient): use Regular Expression for matching url

app/extend/application.js, package.json, test/fixtures/demo/app/controller/home.js, test/fixtures/demo/app/router.js, test/mock_httpclient.test.js
=> fix: should use the copy of mockResult

package.json
错误描述：
egg 项目 执行 npm run test-local
Error: Cannot find module 'methods'
=> 修复依赖包methods 未在 dependencies 中声明

lib/cluster.js, test/cluster.test.js
=> feat: port can be customized

.travis.yml, appveyor.yml, package.json, test/fixtures/demo/app/controller/file.js, test/fixtures/demo/app/controller/user.js, test/fixtures/demo/app/router.js, test/mock_context.test.js
=> test: add post with multipart file test cases

lib/supertest.js, test/app.test.js, test/fixtures/app/app.js, test/fixtures/app/app/router.js
https://github.com/eggjs/egg/pull/2146#issuecomment-369189329
=> feat: mm.app() support server event

README.md, README.zh_CN.md, lib/http_test.js, lib/supertest.js, test/mock_request.test.js
Easy to test response without some header.
=> feat: add unexpectHeader() and expectHeader()

app/extend/application.js, test/fixtures/demo/app/controller/session.js
close https://github.com/eggjs/egg/issues/2231
=> fix: mockSession save

app/extend/application.js, test/format_options.test.js, test/mock_session.test.js
fix https://github.com/eggjs/egg-mock/pull/68#discussion_r175990580
=> fix: mockSession save should not be enumerable

app/middleware/cluster_app_mock.js
=> refactor: middleware use promise-based style

bootstrap.d.ts, index.d.ts
none
- add add bootstrap.d.ts
- update package.json
=> types: add bootstrap.d.ts

.travis.yml, README.md, README.zh_CN.md, app/extend/application.js, appveyor.yml, lib/cluster.js, package.json, test/app.test.js, test/fixtures/app/app/router.js, test/format_options.test.js, test/mock_service.async.js, test/mock_service.test.js
helper function to assert string value in logger
=> feat: add `app.expectLog()` for app and cluster

index.d.ts, package.json
=> chore: add bootstrap.d.ts

LICENSE, app/extend/application.js, bootstrap.js, lib/app.js, lib/context.js, package.json, test/bootstrap.test.js, test/fixtures/app/app/router.js, test/mm.test.js
=> feat: should wait for background task finish on afterEach

app/extend/application.js, lib/context.js, test/bootstrap.test.js
=> fix: make sure backgroundTasksFinished() return promise

bootstrap.js, test/bootstrap.test.js, test/fixtures/app/app/router.js
=> fix: put mock restore at the end

index.d.ts
~~手动复制是因为目前没有办法合并这两个库的定义 ref https://github.com/node-modules/mm/pull/41~~
update: https://github.com/node-modules/mm/pull/42
=> feat: .d.ts 新增继承自 mm 的 api

app/extend/application.js
=> fix: show expectLog last 500 words on assert error

lib/app.js, test/app_proxy.test.js, test/fixtures/messenger-binding/agent.js, test/fixtures/messenger-binding/app.js
=> fix: egg-mock 中 app.messenger.broadcast 的消息，自身无法接收到 #2911

README.md, app/extend/agent.js, app/extend/application.js, lib/mock_httpclient.js, test/mock_agent_httpclient.test.js
add `app.agent.mockHttpclient()`
=> feat: add `app.agent.mockHttpclient()` for agent

.eslintrc, bootstrap.js
=> feat: bootstrap support run on jest env

.autod.conf.js, .travis.yml, lib/app.js, lib/mock_custom_loader.js, package.json, test/fixtures/custom-loader/app/adapter/docker.js, test/fixtures/custom-loader/app/controller/user.js, test/fixtures/custom-loader/app/repository/user.js, test/fixtures/custom-loader/app/router.js, test/fixtures/custom-loader/config/config.default.js, test/fixtures/custom-loader/package.json, test/mock_custom_loader.test.js
=> feat: add mock API for customLoader

app/extend/agent.js, app/extend/application.js, index.js, lib/app.js, lib/cluster.js, lib/mock_http_server.js, lib/mock_httpclient.js, lib/supertest.js, test/app.test.js, test/fixtures/apps/app-throw/app/router.js, test/fixtures/server/app.js, test/fixtures/server/package.json
- require https://github.com/eggjs/egg/pull/3601
- close https://github.com/eggjs/egg/issues/3582
=> fix: should emit server

package.json
=> fix: remove egg-core deps

README.md, README.zh_CN.md, index.d.ts, lib/app.js, lib/mock_httpclient.js, test/fixtures/demo/app/controller/home.js, test/index.test.ts, test/mock_agent_httpclient.test.js, test/mock_httpclient.test.js
```js
app.mockHttpclient(url, 'get', (url, opt) => {
return `mock ${url} with ${opt.data.a}`;
});
```
=> feat: mockHttpclient support fn

app/extend/application.js, test/app.test.js
=> fix: mockLog don't read file

.travis.yml, package.json
两个变动：
1. 不允许把 `async function` mock 成普通的 function，避免一些 mock 造成的测试遗漏；
2. 支持类似 sinon 的 spy https://github.com/node-modules/mm#support-spy
=> feat: upgrade mm@3

.github/workflows/nodejs.yml, README.md, README.zh_CN.md, index.d.ts, index.test-d.ts, package.json, test/mock_httpclient.test.js, test/tsd.test.js
=> feat: add mockLog, expectLog to type define

index.d.ts, index.test-d.ts, lib/http_test.js, lib/mock_httpclient.js, lib/supertest.js, test/mock_httpclient_next.test.js
=> 👌 IMPROVE: Mock httpclient support delay ms and repeat times

test/fixtures/demo_next/app/controller/home.js, test/fixtures/demo_next/app/router.js, test/mock_httpclient_next.test.js
=> 🤖 TEST: Add httpclient streaming mocking

index.d.ts, lib/mock_agent.js, lib/request_call_function.js, package.json, test/mock_httpclient_next.test.js
=> 🐛 FIX: Should use urllib-next package

README.md, lib/utils.js
=> feat: add EGG_FRAMEWORK for bootstrap custom framework

app/extend/application.js, index.test-d.ts, lib/mock_httpclient.js, package.json, test/fixtures/demo/app/controller/file.js, test/fixtures/demo_next/app/controller/home.js, test/mock_context.test.js
=> 📦 NEW: mock context support ctxStorage

.github/workflows/nodejs.yml, app/extend/agent.js, app/extend/application.js, index.d.ts, index.test-d.ts, package.json, test/fixtures/agent/agent.js, test/fixtures/demo_next/app/controller/home.js, test/fixtures/demo_next/app/router.js, test/mock_httpclient_next.test.js
=> 📦 NEW: Allow restore mockAgent only

README.md, README.zh_CN.md, app/extend/application.js, index.d.ts, index.test-d.ts, test/ctx.test.js
Get async local storage in scope is safe.
=> feat: add mockContextScope

app/extend/application.js, package.json, test/fixtures/demo/app/controller/user.js, test/mock_context.test.js
=> feat: upgrade globby to v11

bootstrap.d.ts, bootstrap.js, package.json
https://github.com/eggjs/egg-bin/pull/197
=> feat: remove power-assert

app/extend/application.js, app/middleware/cluster_app_mock.js, lib/app.js, lib/cluster.js, lib/format_options.js, lib/parallel/agent.js, lib/parallel/app.js, lib/parallel/util.js, lib/prerequire.js, package.json, test/cluster.test.js
=> fix: should add egg to peerDependencies

package.json
=> fix: add register.js to files

register.js
=> fix: ignore bootstrap error on non egg project

.gitignore, README.md, README.zh_CN.md, app/extend/application.js, lib/inject_context.js, package.json, register.js, test/fixtures/tegg-app/app.js, test/fixtures/tegg-app/app/modules/foo/LogService.ts, test/fixtures/tegg-app/app/modules/foo/package.json, test/fixtures/tegg-app/config/config.default.js, test/fixtures/tegg-app/config/plugin.js, test/fixtures/tegg-app/package.json, test/fixtures/tegg-app/test/hooks.test.ts, test/fixtures/tegg-app/test/multi_mock_context.test.ts, test/fixtures/tegg-app/test/tegg.test.ts, test/fixtures/tegg-app/test/tegg_context.test.ts, test/fixtures/tegg-app/tsconfig.json, test/fixtures/tegg-app/typing.ts, test/inject_ctx.test.js
=> feat: inject tegg ctx to mocha runner

app/extend/application.js, index.d.ts, index.test-d.ts
=> fix: mockContextScope should return Promise

package.json
=> fix: mocha should be peer deps

lib/supertest.js, test/app.test.js, test/fixtures/app/app/router.js, test/parallel.test.js
superagent not set default ua.
=> fix: add default ua egg-mock/${version}
